### ISSUE TITLE
Is there a generic way to perform reciprocal queries

### ISSUE THREAD

**Issue by andrewsu** [kevinxin90/bte_schema#3]
The following query asks for all genes that are related to a specific GO ID (for "inflammasome").

```
a = ht.query('inflammasome')
node_inflammasome = a['CellularComponent'][0]
seqd = SingleEdgeQueryDispatcher(input_obj=node_inflammasome,
                                 output_cls='Gene',
                                 output_id='bts:entrez',
                                 registry=reg)
seqd.query()
seqd.show_all_nodes()
```

It currently returns zero results.  Presumably this is because mygene.info only queries genes --> GO, not GO --> gene.  Is there an easy and generic way of enabling the reciprocal query?

**Comment by kevinxin90** [comment]
BioThings Explorer can handle queries from both directions for all BioThings APIs.

This issue is simply because I forgot to add gene->CC connection in MyGene.info schema mapping file :)

I have just added that linkage. The result should return all genes related to this GO term now!

**Comment by andrewsu** [comment]
The code snipped above now produces this result:

`['GO:0061702', '338321', '22900', '837', '171389', '22861']`

Looks like that matches the query http://mygene.info/v3/query?q=GO:0061702&species=human.  Just so I understand, where is the human species filter applied within the BTE infrastructure?

**Comment by kevinxin90** [comment]
Yes. For MyGene.info, I specifically add "species=human" for all queries. Otherwise, it just return too many results. For example, if a user input "CDK7" as symbol, this can be converted to 341 Genes representing different species. In order to increase the efficiency of this tool, i specifically restrict the species to human.

I think it might be better to add an additional parameter in the query, so user could get all species data back.

**Comment by kevinxin90** [comment]
The line of code regarding this issue is here: https://github.com/kevinxin90/bte_schema/blob/master/biothings_explorer/apicall.py#L32
